# Lazygit config. Docs: https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md

gui:
  nerdFontsVersion: "3"
  border: "rounded"
  mouseEvents: true
  expandFocusedSidePanel: true
  showCommandLog: false
  timeFormat: "2006-01-02"
  shortTimeFormat: "15:04"
  theme:
    activeBorderColor:
      - green
      - bold
    inactiveBorderColor:
      - white
    selectedLineBgColor:
      - blue
    cherryPickedCommitBgColor:
      - cyan
    unstagedChangesColor:
      - red
git:
  pagers:
    - colorArg: always
      pager: delta --dark --paging=never
  commit:
    signOff: false
  autoFetch: true
  autoRefresh: true
  branchLogCmd: "git log --graph --color=always --abbrev-commit --decorate --date=relative --pretty=medium {{branchName}} --"
  allBranchesLogCmds:
    - git log --graph --all --color=always --abbrev-commit --decorate --simplify-by-decoration
os:
  edit: "nvim {{filename}}"
  editAtLine: "nvim +{{line}} {{filename}}"
  editAtLineAndWait: "nvim +{{line}} {{filename}}"
  open: "open {{link}}"
keybinding:
  universal:
    quit: "q"
    return: "<esc>"
    nextItem: "j"
    prevItem: "k"
  files:
    commitChanges: "c"
    commitChangesWithoutHook: "w"
